dbt_data_marts:
  outputs:
    dev:
      type: duckdb
      path: 'data/local.duckdb'
      schema: abtest
      threads: 1

    prod:
      type: duckdb
      path: 'data/local.duckdb'
      schema: abtest
      threads: 4

  target: dev
