version: 2

models:
  - name: active_abtests
    description: "This model selects data from AB_TEST_DIMENSION and AB_TEST_DASHBOARD, applying filters and transformations relevant to A/B test analysis."
    columns:
      - name: test_name
        description: "Name of the A/B test (lowercased)."
        data_tests:
          - not_null
      - name: test_version
        description: "Version of the A/B test."
        data_tests:
          - not_null
      - name: test_type
        description: "Type of the A/B test."
      - name: test_start_date
        description: "Start date of the A/B test."
        data_tests:
          - not_null
      - name: test_end_date
        description: "End date of the A/B test."
      - name: TEST_STATUS
        description: "Status of the A/B test."
      - name: TEST_METRICS
        description: "Metrics associated with the A/B test."
        data_tests:
          - not_null
